/**
 * Central project data. Add `github` / `demo` URLs here later —
 * the renderer only shows those buttons when a value is present.
 */
const projectsData = [
	{
		id: "no-secrets",
		title: "No Secrets – E-commerce Platform & Admin Panel",
		period: "May 2026 – Present",
		org: "Digital Night Owl",
		description: [
			"Built a pixel-perfect, fully responsive Next.js storefront (from Figma) with product browsing, cart, auth, and GSAP scroll animations.",
			"Paired it with a full admin panel managing products, orders, customers, and CMS content, with Excel/PDF export and a Store Overview dashboard.",
			"Used React Hook Form + Zod and TanStack Query across both for type-safe forms and optimized data fetching.",
		],
		skills: [
			"TanStack Query",
			"Next.js",
			"GSAP",
			"Tailwind CSS",
			"Framer Motion",
			"TypeScript",
			"React Hook Form",
			"Zod",
		],
		skillsMore: 0,
		thumbnail: null,
		github: null,
		demo: null,
	},
	{
		id: "kaaya-prime-realty",
		title: "Kaaya Prime Realty – Website & Admin Panel",
		period: "Apr 2026 – Aug 2026",
		org: "Digital Night Owl",
		description: [
			"Built a pixel-perfect, SEO-focused Next.js site for a Dubai real estate brand — listings, blogs, market reports, and lead generation, with GSAP scroll interactions.",
			"Paired it with an admin panel for managing properties, leads, and content, featuring a Marketing Intelligence dashboard and Tiptap CMS editing.",
			"Used TanStack Query, Zustand, and React Hook Form + Zod for data fetching, state, and type-safe forms across both.",
		],
		skills: [
			"TanStack Query",
			"Next.js",
			"GSAP",
			"Tailwind CSS",
			"Framer Motion",
			"TypeScript",
			"React Hook Form",
			"Google Tag Manager",
			"Zod",
		],
		skillsMore: 0,
		thumbnail: null,
		github: null,
		demo: "https://kaayaprimerealty.com/",
	},
	{
		id: "impact-water",
		title: "Impact Water – 3D E-commerce Platform",
		period: "Mar 2025 – Jun 2026",
		org: "Digital Night Owl",
		description: [
			"Rebuilt the UI of an existing Three.js e-commerce platform for a more responsive, production-ready experience.",
			"Added Zustand-based cart and address management, plus a full Razorpay checkout workflow.",
		],
		skills: [
			"Razorpay",
			"React.js",
			"Zustand",
			"GSAP",
			"Tailwind CSS",
			"Framer Motion",
			"Three.js",
			"TypeScript",
		],
		skillsMore: 0,
		thumbnail: null,
		github: null,
		demo: "https://impactwater.in/",
	},
	// {
	// 	id: "loanzo-dealer-panel",
	// 	title: "Loanzo Dealer Panel",
	// 	period: "Jun 2026 – Jun 2026",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Added Razorpay payment integration and a digital wallet system to an existing loan management dealer portal.",
	// 		"Enabled dealers to add funds, track balances, and view transaction history via optimized REST workflows.",
	// 	],
	// 	skills: [
	// 		"Razorpay",
	// 		"React.js",
	// 		"Redux",
	// 		"Tailwind CSS",
	// 		"Redux Thunk",
	// 	],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: null,
	// },
	// {
	// 	id: "hrms",
	// 	title: "HRMS – Human Resource Management System",
	// 	period: "Apr 2026 – May 2026",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Built a role-based HRMS (Admin/HR/Employee) covering employee, department, project, and announcement management.",
	// 		"Added a Salary Management module with PDF payslips and calendar-based Attendance Management with full history and filtering.",
	// 	],
	// 	skills: [
	// 		"React.js",
	// 		"React Hook Form",
	// 		"TanStack Query",
	// 		"Tailwind CSS",
	// 		"Zod",
	// 	],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: null,
	// },
	// {
	// 	id: "qr-puzzle",
	// 	title: "QR Puzzle – Reward Management Platform",
	// 	period: "Apr 2026 – Apr 2026",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Built a React CRM for creating QR-code puzzle reward campaigns, splitting codes into configurable 4×4–16×16 grids for print/distribution.",
	// 		"Designed the full redemption flow — users reassemble the puzzle, scan it, and receive a verified reward code.",
	// 	],
	// 	skills: ["React.js", "Tailwind CSS", "Shadcn UI"],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: null,
	// },
	// {
	// 	id: "uresia",
	// 	title: "Uresia – Multi-Vendor E-commerce Platform",
	// 	period: "Mar 2026 – Apr 2026",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Redesigned the frontend of an existing multi-vendor platform for a more responsive, intuitive shopping experience.",
	// 		"Improved auth/seller onboarding and built a scalable category-based product listing and checkout flow.",
	// 	],
	// 	skills: ["React.js", "Tailwind CSS"],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: null,
	// },
	{
		id: "dno-crm",
		title: "Digital Night Owl CRM",
		period: "Jan 2026 – Mar 2026",
		org: "Digital Night Owl",
		description: [
			"Built a role-based CRM (Admin/Manager/Employee) from scratch — dashboards, employee/attendance management, and analytics.",
			"Developed a Project Management module (Table/Kanban, billing types, milestone tracking) with a hierarchical Projects → Modules → Bugs workflow.",
			"Added an Employee Portal with live clock-in/out timers, plus Excel/PDF export and type-safe forms via React Hook Form + Zod.",
		],
		skills: [
			"React.js",
			"React Hook Form",
			"TanStack Query",
			"React Paginate",
			"React Calendar",
			"Tailwind CSS",
			"Recharts",
			"Zod",
		],
		skillsMore: 0,
		thumbnail: null,
		github: null,
		demo: null,
	},
	{
		id: "ima-quiz",
		title: "IMA Quiz Application",
		period: "Feb 2026 – Mar 2026",
		org: "Digital Night Owl",
		description: [
			"Built a multilingual (EN/ZH) Next.js quiz app with a configuration-driven engine supporting multiple question types.",
			"Used Zustand for a session-based workflow with persistent, prefillable answers across visits.",
		],
		skills: ["Zustand", "Next.js", "next-intl", "Tailwind CSS"],
		skillsMore: 0,
		thumbnail: null,
		github: null,
		demo: null,
	},
	// {
	// 	id: "zakkuu",
	// 	title: "Zakkuu – Furniture E-commerce Platform",
	// 	period: "Feb 2026 – Mar 2026",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Rebuilt the frontend into a wood-inspired premium theme matching the brand identity.",
	// 		"Delivered responsive product, cart, and checkout pages with Razorpay payment integration.",
	// 	],
	// 	skills: ["Razorpay", "React.js", "Tailwind CSS"],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: "https://zakkuu.com/",
	// },
	// {
	// 	id: "joen-ai-quiz",
	// 	title: "Joen AI Quiz Application",
	// 	period: "Dec 2025 – Jan 2026",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Built an AI-powered quiz app (React, later migrated to Next.js) with a configuration-driven engine and dynamic per-quiz UI.",
	// 		"Added an interactive map-based question type via React Simple Maps, with session persistence and answer prefill using Local Storage.",
	// 	],
	// 	skills: [
	// 		"React.js",
	// 		"Next.js",
	// 		"React Simple Maps",
	// 		"Tailwind CSS",
	// 		"TypeScript",
	// 	],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: "https://quiz.xhost.live/",
	// },
	// {
	// 	id: "sportslivv-admin",
	// 	title: "SportsLivv – Admin Panel",
	// 	period: "Dec 2025 – Jan 2026",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Built an admin panel from scratch for a cricket platform, managing matches, players, and statistics.",
	// 		"Used TanStack Query for data fetching/caching, with role-based auth and advanced filtering.",
	// 	],
	// 	skills: [
	// 		"React.js",
	// 		"TanStack Query",
	// 		"React Paginate",
	// 		"Tailwind CSS",
	// 	],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: null,
	// },
	// {
	// 	id: "physnxt-admin",
	// 	title: "PhysNXT – Admin Panel",
	// 	period: "Nov 2025 – Dec 2025",
	// 	org: "Digital Night Owl",
	// 	description: [
	// 		"Built and maintained the admin panel for a physiotherapy platform managing patients, physiotherapists, and appointments.",
	// 		"Added a booking notifications page and Excel/PDF export across modules with date-range filtering.",
	// 	],
	// 	skills: ["React.js", "Tailwind CSS"],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: null,
	// },
	{
		id: "greencart",
		title: "GreenCart – Grocery Shopping Web App",
		period: "Mar 2025 – Apr 2025",
		org: "QSpiders",
		description: [
			"Full-stack MERN grocery platform with product browsing, cart, and JWT-based auth.",
			"Includes a seller dashboard for product/order management; deployed on Render and MongoDB Atlas.",
		],
		skills: [
			"React.js",
			"Node.js",
			"Tailwind CSS",
			"Express.js",
			"MongoDB",
		],
		skillsMore: 0,
		thumbnail: null,
		github: "https://github.com/urssanjaysingh/GreenCart",
		demo: "https://greencart-8d9l.onrender.com/",
	},
	// {
	// 	id: "foodies-website",
	// 	title: "Foodies Website",
	// 	period: "Nov 2024 – Dec 2024",
	// 	org: "QSpiders",
	// 	description: [
	// 		"A responsive food website built with modern web technologies.",
	// 	],
	// 	skills: ["CSS", "JavaScript", "Bootstrap", "HTML"],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: null,
	// 	demo: null,
	// },
	{
		id: "pizzarush",
		title: "PizzaRush – Pizza Delivery Application",
		period: "Mar 2024 – Apr 2024",
		org: "OasisInfobyte",
		description: [
			"Online pizza ordering platform with auth, a custom pizza builder, and secure payment integration.",
			"Includes inventory/order management and an admin dashboard — built during a Web Development internship.",
		],
		skills: [
			"React.js",
			"Node.js",
			"Cloudinary",
			"Git",
			"Bootstrap",
			"Braintree",
			"Email Service",
			"Express.js",
			"MongoDB",
			"Ant Design",
		],
		skillsMore: 0,
		thumbnail: null,
		github: "https://github.com/urssanjaysingh/PizzaRush",
		demo: "https://pizzarush.onrender.com/",
	},
	// {
	// 	id: "shopnest",
	// 	title: "ShopNest – An E-Commerce Platform",
	// 	period: "Oct 2023 – Nov 2023",
	// 	org: "Personal Project",
	// 	description: [
	// 		"E-commerce platform with account management, categorized product catalog, and advanced filters.",
	// 		"Features intuitive cart management, checkout with order tracking, and an admin panel for product/order management.",
	// 	],
	// 	skills: [
	// 		"React.js",
	// 		"Node.js",
	// 		"Cloudinary",
	// 		"Git",
	// 		"Express.js",
	// 		"MongoDB",
	// 	],
	// 	skillsMore: 0,
	// 	thumbnail: null,
	// 	github: "https://github.com/urssanjaysingh/GreenCart",
	// 	demo: "https://shopnest-jjzh.onrender.com/",
	// },
];

// Exposed globally — no bundler in this project, so plain script tags read this.
window.projectsData = projectsData;
